---
openapi: 3.0.1
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: Authorization
security:
  - ApiKeyAuth: []
info:
  title: API V1
  version: v1
paths:
  "/memories":
    post:
      summary: Needs Authorization header from /auth/login
      tags:
      - Memories
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: memory created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The memory ID.
                  user_id:
                    type: integer
                    description: The memory owner ID.
                  key:
                    type: string
                    description: The memory key.
                  value:
                    type: string
                    description: The memory value.
                  visibility:
                    type: boolean
                    description: The memory visibility.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
                visibility:
                  type: boolean
              required:
              - key
              - value
servers:
- url: http://localhost:3000
- url: https://memory-app-back.herokuapp.com
