version: "3"
services:
  db_pg:
    image: postgres
    container_name: db_pg
    volumes:
      - db_pg_volume:/data/postgres

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5444:5432"

  rails_server:
    build:
      context: "."
      dockerfile: "Dockerfile_rails"
    container_name: rails_server
    volumes:
      - ./volume/memory-app-rails:/app
    depends_on:
      - db_pg
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      RAILS_MASTER_KEY: "a667717bf0a47475b0582547379c816d"
    tty: true
    command: rails server -b 0
    ports:
      - "3333:3000"

volumes:
  db_pg_volume:
# docker-compose build
# docker-compose up -d
# docker exec -it rails bash
# railss
