version: "3"
services:
  db_memory_app:
    image: postgres
    container_name: db_memory_app
    volumes:
      - db_memory_app_volume:/data/postgres

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      CC_TEST_REPORTER_ID: d341aee07bf1ff51e397e80382d5ff14905e9f9b620ec5562094a9662f279755
    ports:
      - "5444:5432"

  memory_app_back:
    image: edimossilva/memory_app_rails
    container_name: memory_app_back
    volumes:
      - ./app:/app
    depends_on:
      - db_memory_app
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      RAILS_MASTER_KEY: "a667717bf0a47475b0582547379c816d"
    tty: true
    command: rails server -b 0
    ports:
      - "3333:3000"

volumes:
  db_memory_app_volume:
# docker-compose build
# docker-compose up -d
# docker-compose exec memory_app_back rake db:create
# docker-compose exec  memory_app_back rake db:migrate
# docker-compose exec  memory_app_back rspec
# exitcode=$(if [ "$SEMAPHORE_THREAD_RESULT" == "passed" ]; then echo 0; else echo 1; fi)
# ./cc-test-reporter after-build --exit-code $exitcode
