version: "3"
services:
  db_memory_app:
    image: postgres
    container_name: db_memory_app
    volumes:
      - db_memory_app_volume:/data/postgres

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5444:5432"

  memory_app_back:
    image: edimossilva/memory_app_rails
    container_name: memory_app_back
    volumes:
      - ./app:/app
    depends_on:
      - db_memory_app
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      RAILS_MASTER_KEY: "a667717bf0a47475b0582547379c816d"
    tty: true
    command: rails server -b 0
    ports:
      - "3333:3000"

volumes:
  db_memory_app_volume:
# docker-compose build
# docker-compose up -d
# docker-compose exec memory_app_back rake db:create
# docker-compose exec memory_app_back rake db:migrate
# docker-compose exec memory_app_back rspec
