version: "3"
services:
  db_memory_app:
    image: postgres
    container_name: db_memory_app
    volumes:
      - db_memory_app_volume:/data/postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5444:5432"

  memory_app_back:
    image: edimossilva/memory_app_rails
    container_name: memory_app_back
    volumes:
      - ./app:/app
    depends_on:
      - db_memory_app
    env_file:
      - .env
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      DATABASE_URL: "db_memory_app"
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    tty: true
    command: sh
    ports:
      - "3000:3000"

volumes:
  db_memory_app_volume:
# docker-compose build
# docker-compose up -d
# docker-compose exec memory_app_back rake db:create
# docker-compose exec memory_app_back rake db:migrate
# docker-compose exec memory_app_back rspec
