default: &default
  adapter: postgresql
  encoding: unicode
  database: boiler_plate_database
  pool: 5
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
